export const USERPROFILE_LOADING = 'USERPROFILE_LOADING'
export const USERPROFILE_SUCCESS = 'USERPROFILE_SUCCESS'
export const USERPROFILE_ERROR = 'USERPROFILE_ERROR'

export const MYTRANSACTIONS_LOADING = 'MYTRANSACTIONS_LOADING'
export const MYTRANSACTIONS_SUCCESS = 'MYTRANSACTIONS_SUCCESS'
export const MYTRANSACTIONS_ERROR = 'MYTRANSACTIONS_ERROR'

export const RAJAONGKIRPROVINCE_LOADING = 'RAJAONGKIRPROVINCE_LOADING'
export const RAJAONGKIRPROVINCE_SUCCESS = 'RAJAONGKIRPROVINCE_SUCCESS'
export const RAJAONGKIRPROVINCE_ERROR = 'RAJAONGKIRPROVINCE_ERROR'

export const RAJAONGKIRCITY_LOADING = 'RAJAONGKIRCITY_LOADING'
export const RAJAONGKIRCITY_SUCCESS = 'RAJAONGKIRCITY_SUCCESS'
export const RAJAONGKIRCITY_ERROR = 'RAJAONGKIRCITY_ERROR'

export const SHIPPINGADDRESS_LOADING = 'SHIPPINGADDRESS_LOADING'
export const SHIPPINGADDRESS_SUCCESS = 'SHIPPINGADDRESS_SUCCESS'
export const SHIPPINGADDRESS_ERROR = 'SHIPPINGADDRESS_ERROR' 

export const DATASTATISTIC_LOADING = 'DATASTATISTIC_LOADING'
export const DATASTATISTIC_SUCCESS = 'DATASTATISTIC_SUCCESS'
export const DATASTATISTIC_ERROR = 'DATASTATISTIC_ERROR'

export const USERSTRANSACTIONS_LOADING = 'USERSTRANSACTIONS_LOADING'
export const USERSTRANSACTIONS_SUCCESS = 'USERSTRANSACTIONS_SUCCESS'
export const USERSTRANSACTIONS_ERROR = 'USERSTRANSACTIONS_ERROR'

export const WAREHOUSEINVENTORY_LOADING = 'WAREHOUSEINVENTORY_LOADING'
export const WAREHOUSEINVENTORY_SUCCESS = 'WAREHOUSEINVENTORY_SUCCESS'
export const WAREHOUSEINVENTORY_ERROR = 'WAREHOUSEINVENTORY_ERROR'

export const FLASHSALEEVENT_LOADING = 'FLASHSALEEVENT_LOADING'
export const FLASHSALEEVENT_SUCCESS = 'FLASHSALEEVENT_SUCCESS'
export const FLASHSALEEVENT_ERROR = 'FLASHSALEEVENT_ERROR'  

export const CHECKOUTSHIPPINGADDRESS_LOADING = 'CHECKOUTSHIPPINGADDRESS_LOADING'
export const CHECKOUTSHIPPINGADDRESS_SUCCESS = 'CHECKOUTSHIPPINGADDRESS_SUCCESS'
export const CHECKOUTSHIPPINGADDRESS_ERROR = 'CHECKOUTSHIPPINGADDRESS_ERROR' 