  
export const FLASHSALE_LOADING = 'FLASHSALE_LOADING'
export const FLASHSALE_SUCCESS = 'FLASHSALE_SUCCESS'
export const FLASHSALE_ERROR = 'FLASHSALE_ERROR'  

export const BESTSELLERPRODUCTS_LOADING = 'BESTSELLERPRODUCTS_LOADING'
export const BESTSELLERPRODUCTS_SUCCESS = 'BESTSELLERPRODUCTS_SUCCESS'
export const BESTSELLERPRODUCTS_ERROR = 'BESTSELLERPRODUCTS_ERROR'