export const CART_LOADING = 'CART_LOADING'
export const CART_LOADED = 'CART_LOADED'
export const CART_ERROR = 'CART_ERROR'

export const UPDATE_CART_LOADING = 'UPDATE_CART_LOADING'
export const UPDATE_CART_LOADED = 'UPDATE_CART_LOADED'
export const UPDATE_CART_ERROR = 'UPDATE_CART_ERROR'

export const DELETE_CART_LOADING = 'DELETE_CART_LOADING'
export const DELETE_CART_LOADED = 'DELETE_CART_LOADED'
export const DELETE_CART_ERROR = 'DELETE_CART_ERROR'

export const ADD_CART_LOADING = 'ADD_CART_LOADING'
export const ADD_CART_LOADED = 'ADD_CART_LOADED'
export const ADD_CART_ERROR = 'ADD_CART_ERROR'

export const ADD_TRANSACTION_LOADING = 'ADD_TRANSACTION_LOADING'
export const ADD_TRANSACTION_ERROR = 'ADD_TRANSACTION_ERROR'
export const ADD_TRANSACTION_LOADED = 'ADD_TRANSACTION_LOADED'


export const GET_ALL_PRODUCT_LOADING='GET_ALL_PRODUCT_LOADING'
export const GET_ALL_PRODUCT_ERROR='GET_ALL_PRODUCT_ERROR'
export const GET_ALL_PRODUCT_LOADED='GET_ALL_PRODUCT_LOADED'